# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  PROJECT_PATH: "./ACME Mono/ACME.UI.Web/ACME.UI.Web.csproj"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "$PROJECT_PATH"
    - name: Build
      run: dotnet build "$PROJECT_PATH" --no-restore 
    - name: Test
      run: dotnet test "./ACME Mono/ACME.sln" --no-build --verbosity normal
